version: 2.1
orbs:
  node: circleci/node@5.0.0
  codecov: codecov/codecov@3.2.2
  gitleaks: upenn-libraries/gitleaks@1.0.0
jobs:

  scan:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          mkdir .temp
          cd .temp
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.2.7/gitleaks_8.2.7_linux_x64.tar.gz
          tar xf gitleaks_8.2.7_linux_x64.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          rm -rf .temp
          ls 
          cd ..
          gitleaks detect

         




  build:



    docker:
      - image: node:16.13.0

    working_directory: ~/repo

    steps:

      - checkout

      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

      - run: npm run test:coverage

      - codecov/upload:
          file: './coverage/clover.xml'
        
      - run: npm run build

      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public
workflows:
  version: 2
  build_and_test:
    jobs:
      - scan
      - build
   